name: Testing with Kotlin

on:
  push:
    branches: [ master ]

env:
  JAVA_VERSION: '11'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build & Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build test --no-daemon

